### ISSUE TITLE
config.get('BACKEND'), AttributeError: 'NoneType' object has no attribute 'startswith

### ISSUE THREAD

**Issue by antonizoon** [tofay/mediagoblin-indexedsearch#1]
It looks like it's trying to get a config option to figure out what the setting of BACKEND is, but it fails to find the config. What is that all about?

```
    app = context.app_context.create()
  File "/srv/eikonos.org/mediagoblin/lib/python3.4/site-packages/PasteDeploy-1.5.2-py3.4.egg/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/srv/eikonos.org/mediagoblin/lib/python3.4/site-packages/PasteDeploy-1.5.2-py3.4.egg/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/srv/eikonos.org/mediagoblin/lib/python3.4/site-packages/PasteDeploy-1.5.2-py3.4.egg/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "./mediagoblin/app.py", line 365, in paste_app_factory
    mgoblin_app = hook_transform('wrap_wsgi', mgoblin_app)
  File "./mediagoblin/tools/pluginapi.py", line 365, in hook_transform
    result = callable(result)
  File "./mediagoblin/plugins/indexedsearch/__init__.py", line 64, in setup_engine
    get_engine().update_index()
  File "./mediagoblin/plugins/indexedsearch/__init__.py", line 77, in get_engine
    backend_module = importlib.import_module(config.get('BACKEND'))
  File "/srv/eikonos.org/mediagoblin/lib64/python3.4/importlib/__init__.py", line 100, in import_module
    if name.startswith('.'):
AttributeError: 'NoneType' object has no attribute 'startswith
```

**Comment by antonizoon** [comment]
I guess it has to be set to BACKEND='whoosh' ?

https://github.com/tofay/mediagoblin-indexedsearch/blob/master/indexedsearch/backends/whoosh.py

**Comment by antonizoon** [comment]
When I hardcode it to use whoosh, the module has no attribute Engine?

```
Loading paste environment: config:/srv/eikonos.org/mediagoblin/paste.ini
Traceback (most recent call last):
  File "/srv/eikonos.org/mediagoblin/lib/python3.4/site-packages/PasteDeploy-1.5.2-py3.4.egg/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/srv/eikonos.org/mediagoblin/lib/python3.4/site-packages/PasteDeploy-1.5.2-py3.4.egg/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/srv/eikonos.org/mediagoblin/lib/python3.4/site-packages/PasteDeploy-1.5.2-py3.4.egg/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/srv/eikonos.org/mediagoblin/lib/python3.4/site-packages/PasteDeploy-1.5.2-py3.4.egg/paste/deploy/loadwsgi.py", line 203, in invoke
    app = context.app_context.create()
  File "/srv/eikonos.org/mediagoblin/lib/python3.4/site-packages/PasteDeploy-1.5.2-py3.4.egg/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/srv/eikonos.org/mediagoblin/lib/python3.4/site-packages/PasteDeploy-1.5.2-py3.4.egg/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/srv/eikonos.org/mediagoblin/lib/python3.4/site-packages/PasteDeploy-1.5.2-py3.4.egg/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "./mediagoblin/app.py", line 365, in paste_app_factory
    mgoblin_app = hook_transform('wrap_wsgi', mgoblin_app)
  File "./mediagoblin/tools/pluginapi.py", line 365, in hook_transform
    result = callable(result)
  File "./mediagoblin/plugins/indexedsearch/__init__.py", line 64, in setup_engine
    get_engine().update_index()
  File "./mediagoblin/plugins/indexedsearch/__init__.py", line 78, in get_engine
    return backend_module.Engine(**config)
AttributeError: 'module' object has no attribute 'Engine'
```

**Comment by tofay** [comment]
Hi. How have you installed the plugin? Which version of mediagoblin are you running?

The backend should be `indexedsearch.backends.whoosh` be default. I've just added some setup instructions to the readme - please can you try installing the plugin with those instructions and see if that works?
